services:
  - type: web
    name: qrglyph
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 app:app"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: GSB_API_KEY
        sync: false
